### ISSUE TITLE
win下运行测试

### ISSUE THREAD

**Issue by nobodxbodon** [MulanRevive/prototype#5]
```
>python 测试.py
Traceback (most recent call last):
  File "测试.py", line 57, in <module>
    进程表[文件] = subprocess.Popen(["./中.py", 路径 + 文件], stdout=subprocess.PIPE)
  File "C:\Users\win7_laptop\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\win7_laptop\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application
```

**Comment by nobodxbodon** [comment]
已实现 win 下运行测试：https://gitee.com/MulanRevive/mulan-rework/issues/I1U2HP，包括使用原始 ulang-0.2.2.exe 验证功能。
